=== nnnn20430/mindcraft_server_management_repo/compile/nginx/hg/nginx.org/dtd/i18n.dtd
<!--
  Copyright (C) Igor Sysoev
  Copyright (C) Nginx, Inc.
  -->

<!ELEMENT  i18n         (text+) >

<!ELEMENT  text         (item+) >
<!ATTLIST  text
           lang         CDATA #REQUIRED
>

<!ELEMENT  item         ANY>
<!ATTLIST  item
           id           CDATA #REQUIRED
>

<!ELEMENT  origin       (#PCDATA) >

=== nnnn20430/mindcraft_server_management_repo/compile/nginx/hg/nginx.org/xml/i18n.xml
<!--
  Copyright (C) Igor Sysoev
  Copyright (C) Nginx, Inc.
  -->

<!DOCTYPE i18n SYSTEM "../dtd/i18n.dtd">

<i18n>

<text lang="en">
<item id="and">and</item>
<item id="author">written by</item>
<item id="editor">edited by</item>
<item id="translator">translated by</item>
<item id="syntax">Syntax</item>
<item id="default">Default</item>
<item id="context">Context</item>
<item id="context.any">any</item>
<item id="directive.version">This directive appeared in version</item>
<item id="directive.versions">This directive appeared in versions</item>
<item id="dirindex">Alphabetical index of directives</item>
<item id="varindex">Alphabetical index of variables</item>
<item id="outdated">This translation may be out of date.
Check the <origin>English version</origin>
for recent changes.</item>
</text>

<text lang="ru">
<item id="and">и</item>
<item id="author">автор:</item>
<item id="editor">редактор:</item>
<item id="translator">перевод:</item>
<item id="syntax">Синтаксис</item>
<item id="default">Умолчание</item>
<item id="context">Контекст</item>
<item id="context.any">любой</item>
<item id="directive.version">Эта директива появилась в версии</item>
<item id="directive.versions">Эта директива появилась в версиях</item>
<item id="dirindex">Алфавитный указатель директив</item>
<item id="varindex">Алфавитный указатель переменных</item>
<item id="outdated">Этот перевод может быть устаревшим.
Смотрите <origin>английскую версию</origin>
для ознакомления с последними изменениями.</item>
</text>

<text lang="cn">
<item id="and">和</item>
<item id="author">作者:</item>
<item id="editor">编辑:</item>
<item id="translator">翻译:</item>
<item id="syntax">语法</item>
<item id="default">默认值</item>
<item id="context">上下文</item>
<item id="context.any">任意</item>
<item id="directive.version">这个指令出现在版本</item>
<item id="directive.versions">这个指令出现在版本</item>
<item id="dirindex">指令目录</item>
<item id="outdated">翻译内容可能已经过旧。
你可以通过 <origin>英文版本</origin>
查看最近的更新。</item>
</text>

<text lang="ja">
<item id="author">作成:</item>
<item id="translator">翻訳:</item>
</text>

<text lang="he">
<item id="author">נכתב על ידי</item>
<item id="translator">תורגם על ידי</item>
</text>

<text lang="tr">
<item id="author">yazan:</item>
<item id="translator">çeviren:</item>
</text>

<text lang="it">
<item id="and">e</item>
<item id="author">scritto da</item>
<item id="editor">a cura di</item>
<item id="translator">tradotto da</item>
<item id="dirindex">Elenco alfabetico delle direttive</item>
<item id="outdated">Questa traduzione potrebbe essere obsoleta.
Verifica la <origin>versione in inglese</origin>
per gli aggiornamenti piu' recenti.</item>
</text>

</i18n>
